runtime: custom
vm: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

handlers:
- url: /.*
  script: IGNORED
  secure: always