server:
  applicationContextPath: /api
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

database:
  driverClass: com.mysql.jdbc.Driver
  user: newuser
  password: password
  url: jdbc:mysql://localhost:3306/coop
  properties:
    characterEncoding: UTF-8
    connectionTimeout: 5000
    userUnicode: true
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  minSize: 10
  maxSize: 100
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute