server:
  applicationContextPath: /_ah/
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: coop.keystore
      keyStorePassword: idandc13
      validateCerts: false
      supportedProtocols: [TLSv1.2, SSLv2Hello]

  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

database:
  driverClass: com.mysql.jdbc.Driver
  user: coop_application
  password: YzExNTU2YWYtNGM0Ni00ZGViLWEwODMtMmRhMTYwMmJmYzBkCg
  url: jdbc:mysql://173.194.239.39:3306/coop
  properties:
    characterEncoding: UTF-8
    connectionTimeout: 5000
    userUnicode: true
  maxWaitForConnection: 30s
  validationQuery: "SELECT 1"
  minSize: 10
  maxSize: 100
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute

auth:
  secret: YWI1MTg1YTctNGJjMi00YzcyLTkyOWQtNDZjNjJiZGRiZDE1

facebook:
  client_id: 228671707475003
  secret: b73febb6f94c991a90e78da47b35c379

google:
  client_id: 460438236970-uecf0olbtirtp55r10a4cuev2ntiuep7.apps.googleusercontent.com
  secret: VrwbbrmJR968kXX-YeEIVBQ3
  